# Generated by Django 4.2.3 on 2024-02-23 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(choices=[('Фильмы', 'Фильмы'), ('Музыка', 'Музыка'), ('Игры', 'Игры'), ('Спорт', 'Спорт'), ('Прогулки', 'Прогулки'), ('Путешествия', 'Путешествия'), ('Благотворительность', 'Благотворительность'), ('Учёба', 'Учёба'), ('Книги', 'Книги'), ('Саморазвитие', 'Саморазвитие'), ('Фильмы', 'Фильмы'), ('Фильмы', 'Фильмы')], default='Фильмы', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografy', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото профиля')),
                ('hobbies', models.ManyToManyField(to='web.interests', verbose_name='Хобби')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
