# Generated by Django 4.2.3 on 2024-02-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
