# Generated by Django 4.2.3 on 2024-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_profile_biografy_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='images', verbose_name='Фото профиля'),
        ),
    ]
