# Generated by Django 4.2.3 on 2024-02-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='images', verbose_name='Фото профиля'),
        ),
    ]
