# Generated by Django 4.2.3 on 2024-02-27 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_matching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='matched_user',
        ),
        migrations.AddField(
            model_name='matching',
            name='dislike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='дизлайки', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matching',
            name='like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='лайки', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
