# Generated by Django 4.2.3 on 2024-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_matching_matched_user_matching_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='dislike',
            field=models.CharField(max_length=10000, verbose_name='дизлайки'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='like',
            field=models.CharField(max_length=10000, verbose_name='лайки'),
        ),
    ]
