# Generated by Django 4.2.3 on 2024-02-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_matching_dislike_alter_matching_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='dislike',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='дизлайки'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='like',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='лайки'),
        ),
    ]
