# Generated by Django 4.2.3 on 2024-02-27 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_alter_matching_dislike_alter_matching_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_users', to=settings.AUTH_USER_MODEL)),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.matching')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_users', to=settings.AUTH_USER_MODEL)),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.matching')),
            ],
        ),
    ]
