# Generated by Django 4.2.3 on 2024-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_matching_dislike_remove_matching_like_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='matching',
        ),
        migrations.AddField(
            model_name='matching',
            name='dislike',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='дизлайки'),
        ),
        migrations.AddField(
            model_name='matching',
            name='like',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='лайки'),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
