# Generated by Django 4.2.3 on 2024-03-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_like_liked_user_remove_like_matching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='dislike',
            field=models.IntegerField(blank=True, null=True, verbose_name='дизлайки'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='like',
            field=models.IntegerField(blank=True, null=True, verbose_name='лайки'),
        ),
    ]
