# Generated by Django 4.2.3 on 2024-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_matching_dislike_alter_matching_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='dislike',
            field=models.IntegerField(max_length=1000000, null=True, verbose_name='дизлайки'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='like',
            field=models.CharField(max_length=1000000, null=True, verbose_name='лайки'),
        ),
    ]
