# Generated by Django 4.2.3 on 2024-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_matching_dislike_alter_matching_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='dislike',
            field=models.IntegerField(null=True, verbose_name='дизлайки'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='like',
            field=models.IntegerField(null=True, verbose_name='лайки'),
        ),
    ]
